// <auto-generated />
namespace Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NameForeignKeyFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameForeignKeyFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201301081122492_NameForeignKeyFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
